### PR TITLE
fix 2016 performance video tab

### PR DESCRIPTION
**Pull request by imarijr**

### CODE REVIEW

**Comment by mariacec1150** [comment]
Good morning, Imari,

Can you go ahead and merge the pull request for the video fix? I can't seem
to do it.

Dr. Lucero

Cecilia Lucero, Ph.D.
Academic Advisor
<http://fys.nd.edu/fys-resources/first-year-advisors/dr-cecilia-lucero/>, First
Year of Studies
Co-Director, Balfour-Hesburgh Scholars Program
University of Notre Dame
214 Coleman Morse Center
574.631.2515

Schedule an Appointment <http://firstyear.nd.edu/lucero>

https://nd.digication.com/cecilia_lucero_ph_d/Welcome/published

**Comment by imarijr** [comment]
I tried but I don't have "write" permission. It could be because I am only
a collaborator on the sssnd github and not the actual showsomeskin one.

**Comment by mariacec1150** [comment]
Hmm. Let me ask Taylor about this. When I make changes on github, I change
it on the Master branch and changes seem to happen automatically.


Cecilia Lucero, Ph.D.
Academic Advisor
<http://fys.nd.edu/fys-resources/first-year-advisors/dr-cecilia-lucero/>, First
Year of Studies
Co-Director, Balfour-Hesburgh Scholars Program
University of Notre Dame
214 Coleman Morse Center
574.631.2515

Schedule an Appointment <http://firstyear.nd.edu/lucero>

https://nd.digication.com/cecilia_lucero_ph_d/Welcome/published

**Comment by imarijr** [comment]
I believe that is because you are on the main repository, but I am only on
a fork (copy) of the main one. That's why I had to do a pull request to
merge them. If necessary, I can come by sometime this week to figure it out.

**Pull request merged**
